trufnetwork/docs

- billing.mdx
- data-types.mdx
- home.mdx
- how-to-consume.mdx
- incentive-system.mdx
- mint.json
- node-operator-guide.mdx
- node-upgrade.mdx
- troubleshooting-channels.mdx
resolves: https://github.com/truf-network/docs/issues/17
resolves: https://github.com/truf-network/docs/issues/18
resolves: https://github.com/truf-network/docs/issues/19
resolves: https://github.com/truf-network/docs/issues/20
resolves: https://github.com/truf-network/docs/issues/21
resolves: https://github.com/truf-network/docs/issues/22
Writing new section for Node operators here:
Live Demo: https://trufnetwork-docs-nodeoperator.mintlify.app/node-operator-guide
> docs: node operator

- changelog.mdx
- developer-guide.mdx
- home.mdx
- mint.json
- sdks.mdx
resolves: https://github.com/truf-network/docs/issues/24
resolves: https://github.com/truf-network/docs/issues/25
resolves: https://github.com/truf-network/docs/issues/26
resolves: https://github.com/truf-network/docs/issues/27
added the developer section here
No Live URL this time, as the pro plan trial is expired
> docs: developer

- README.md
- bounties-overview.mdx
- data-consumer-guide.mdx
- data-provider-guide.mdx
- home.mdx
- mint.json
resolves: https://github.com/truf-network/truf-network/issues/16
resolves: https://github.com/truf-network/truf-network/issues/19
add new section for bounty here
> docs: developer bounties

- data-consumer-guide.mdx
- data-provider-guide.mdx
- developer-guide.mdx
- home.mdx
- how-to-consume.mdx
- node-operator-guide.mdx
- sdks.mdx
- troubleshooting-channels.mdx
resolves: https://github.com/trufnetwork/truf-network/issues/39
previous's PR: https://github.com/trufnetwork/truf-network/pull/40
> docs: update documentation references to the new organization

- bounties-overview.mdx
- mint.json
- sdks.mdx
- writing-adapters.mdx
resolves: https://github.com/trufnetwork/truf-network/issues/55
> docs: guide to write adapters code

- writing-adapters.mdx
- related to https://github.com/trufnetwork/truf-network/issues/56
> chore: adjust py sdk reference

- ecosystem-partners.mdx
resolves https://github.com/trufnetwork/truf-network/issues/117
> fix: view correct image path in production

- get-truf-token.mdx
- mint.json
resolves: https://github.com/trufnetwork/docs/issues/43
- Added TRUF token page
> docs: TRUF token

- get-truf-token.mdx
resolves https://github.com/trufnetwork/truf-network/issues/132
> docs: view updated info for truf token docs

- bridge.mdx
- governance.mdx
- home.mdx
- mint.json
resolves: https://github.com/trufnetwork/truf-network/issues/138
resolves: https://github.com/trufnetwork/docs/issues/49
- Added new page for governance and bridge
- Redirect the logo URL into truf.network page
> docs: governance and bridge

- abstract.mdx
- introduction-overview.mdx
- mint.json
resolves: https://github.com/trufnetwork/docs/issues/55
resolves: https://github.com/trufnetwork/docs/issues/56
resolves: https://github.com/trufnetwork/docs/issues/57
- Add abstract and introduction
> docs: whitepaper

- media-kit.mdx
resolves https://github.com/trufnetwork/truf-network/issues/154
> docs: open logo URLs in media kit page

- token-governance/get-truf-token.mdx
resolves https://github.com/trufnetwork/truf-network/issues/197
> docs: view list of exchanges

- mint.json
resolves https://github.com/trufnetwork/truf-network/issues/244
> docs: view roadmap

- sdks.mdx
resolves: https://github.com/trufnetwork/sdk-js/issues/35
This pull request includes updates to the installation and usage examples in the `sdks.mdx` file for the Truf Network SDK. The changes primarily focus on updating the package name, modifying the initialization process, and refining the code examples.
* Updated the package name from `@trufnetwork/truf-node-sdk-js` to `@trufnetwork/sdk-js`.
* Modified the client initialization to use `endpoint` and `signerInfo` instead of `privateKey` and `providerUrl`.
* Added wallet creation example using `Wallet` class.
* Changed `StreamId.fromName` to `StreamId.fromString` for loading streams.
* Simplified the logging of record values by directly accessing `record.value`.
* Updated the reference to detailed examples and usage patterns to include …
> docs: updated sdk-js package name and example

- README.md
resolves: https://github.com/trufnetwork/docs/issues/95
> docs: view guide for developer facing network issues

- sdks.mdx
resolves: https://github.com/trufnetwork/node/issues/934
> docs: sdk guide usinng TRUF.NETWORK v2

- node-operator-guide.mdx
resolves: https://github.com/trufnetwork/node/issues/934
> docs: Add clone repo as first step and quick start guide

- sdks.mdx
resolves: https://github.com/trufnetwork/docs/issues/115
> docs: use SDK with local node guide

- sdks.mdx
resolves: https://github.com/trufnetwork/docs/issues/120
> docs: information about streams creation permission

- sdks.mdx
resolves https://github.com/trufnetwork/truf-network/issues/862
> docs: view data fetching and conceptual examples in sdk docs
